// Vercel Serverless Function: GET /api/firstrun?user=<unix-username>&token=<access-token>
//
// Returns a cloud-init user-data snippet pre-filled with the project's
// service-account key (from SODAT_SERVICE_ACCOUNT_JSON_B64) and the Pi
// Imager username. Pi Imager v2.0+ ships cloud-init instead of the legacy
// firstrun.sh; the endpoint name kept for URL stability.
//
// Access is gated by SODAT_ACCESS_TOKEN. Lab admins distribute the token as
// part of the URL (https://<host>/?token=…) so researchers don't type it,
// but knowing the URL without the token can't extract the SA key.
// Token rotation = change the env var and redeploy.
//
// The cloud-init template is inlined below to keep Vercel function bundling
// out of the failure surface — no includeFiles, no readFileSync.

import { timingSafeEqual } from "node:crypto";
import { decodeServiceAccountCreds, FILE_ID_RE } from "../lib/sa_auth.js";

// Linux usernames: lowercase letter first, then [a-z0-9_-], up to 32 chars.
const USER_RE = /^[a-z][a-z0-9_-]{0,31}$/;

// Sensor types the project currently supports. Must stay in sync with
// src/sensors/*.py and with KNOWN_SENSORS in docs/index.html (Step 3 checkboxes).
// (Mock is intentionally excluded — it's for unit tests, not field deployment.)
const KNOWN_SENSORS = new Set([
  "BME280", "TDSN7200", "TDSN7300", "IWS660CS", "Camera", "SerialJSON",
]);

// Cloud-init user-data snippet. String.raw keeps any future backslash
// line-continuations inside the embedded bash literal. Placeholders
// __SODAT_USER__, __SA_JSON_B64__, __SODAT_SENSORS__, __SPREADSHEET_ID__
// are filled in below.
const TEMPLATE = String.raw`# ============================================================================
# Sodat Sensor SFC — cloud-init user-data snippet (zero-touch SD-card setup)
# ============================================================================
#
# DO NOT EDIT THIS FILE BY HAND on a researcher PC. It is a snippet meant to
# be appended to the 'user-data' file that Raspberry Pi Imager v2.0+ writes
# to the SD card's "bootfs" partition (when you used the OS-customisation
# panel).
#
# The web setup page generates a ready-to-paste copy of this file with your
# project's service_account.json already embedded as base64. Use that — do
# not edit this template by hand unless you are the maintainer.
# ============================================================================

# >>> BEGIN SODAT PASTE — APPEND TO /boot/firmware/user-data >>>
# Sodat first-boot bootstrap. Safe to re-apply: the wizard replaces content
# between the BEGIN/END SODAT PASTE markers. Do not touch the markers.

write_files:
  - path: /etc/sodat-firstrun.env
    owner: root:root
    permissions: '0600'
    content: |
      SODAT_USER=__SODAT_USER__
      SODAT_SENSORS=__SODAT_SENSORS__
      SODAT_SPREADSHEET_ID=__SPREADSHEET_ID__
      SODAT_DATA_FOLDER_ID=__DATA_FOLDER_ID__
      SODAT_IMAGES_FOLDER_ID=__IMAGES_FOLDER_ID__
  - path: /etc/sodat-firstrun/service_account.json
    owner: root:root
    permissions: '0600'
    encoding: b64
    content: __SA_JSON_B64__
  - path: /usr/local/sbin/sodat-firstrun.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      # Sodat first-boot bootstrap, invoked by cloud-init's runcmd phase.
      # cloud-init runs runcmd as root, so we don't need sudo here — Pi Imager
      # v2's user-data does not grant the created user NOPASSWD sudo, and a
      # plain "sudo bash" inside this script would block on a password prompt
      # with no tty (which is what happened on the first deploy).
      set -u
      SODAT_LOG=/var/log/sodat-firstrun.log
      exec >>"$SODAT_LOG" 2>&1
      echo "=== sodat firstrun: $(date -Is) (clock may be unsynced) ==="

      # Load SODAT_USER / SODAT_SENSORS written above.
      . /etc/sodat-firstrun.env

      # 1. Trigger NTP and wait for the clock to actually sync. Pi 5 boots with
      # an unset RTC, so the first cloud-init runcmd typically runs ~4 weeks in
      # the past, which then breaks apt's sig-validity check and HTTPS certs.
      timedatectl set-ntp true 2>/dev/null || true
      for i in $(seq 1 60); do
          [ "$(timedatectl show -p NTPSynchronized --value 2>/dev/null)" = "yes" ] && break
          sleep 5
      done
      echo "post-ntp wait: $(date -Is) (NTPSynchronized=$(timedatectl show -p NTPSynchronized --value 2>/dev/null))"

      # 1b. Wi-Fi initialisation. Transient settings only — both are reset
      # on reboot. The persistent equivalents are installed later by
      # 01_install_update.sh (raspi-config nonint do_wifi_country JP) and
      # by /usr/local/sbin/wlan-keepalive.sh (re-disables power save
      # every 5 min). The reason we set them here too: 01_install_update
      # hasn't run yet during the GitHub reach test that follows.
      iw reg set JP 2>/dev/null || true
      iw dev wlan0 set power_save off 2>/dev/null || true

      # 1b'. Mark every preconfigured Wi-Fi connection as hidden. AOI's
      # "keioaoinet" is a hidden SSID; Pi Imager's OS-customisation UI
      # has no checkbox for that, so the connection file it writes leaves
      # wifi.hidden=no and the station never sends probe-requests for
      # the SSID — association then never completes. Setting hidden=yes
      # on visible SSIDs is harmless (just adds active probing).
      for conn in $(nmcli -t -f NAME,TYPE connection show 2>/dev/null | awk -F: '$2=="802-11-wireless"{print $1}'); do
          nmcli connection modify "$conn" wifi.hidden yes 2>/dev/null || true
          nmcli connection up "$conn" 2>/dev/null || true
      done

      # 1c. Wait for wlan0 to actually associate. Without this, the curl
      # reach test below races the wpa_supplicant up-event and just times
      # out with no useful log. On failure, dump the link + reg + route
      # state so we can diagnose remotely from /var/log/sodat-firstrun.log.
      WLAN_OK=no
      for i in $(seq 1 60); do
          if iw dev wlan0 link 2>/dev/null | grep -q '^Connected to'; then
              WLAN_OK=yes; break
          fi
          sleep 2
      done
      echo "post-wlan wait: $(date -Is) WLAN_OK=$WLAN_OK"
      echo "--- diagnostic dump ---"
      iw reg get 2>/dev/null | head -6
      iw dev wlan0 link 2>/dev/null | head -10
      ip -4 addr show wlan0 2>/dev/null | grep inet || echo "(no IPv4 on wlan0)"
      ip route 2>/dev/null | grep default || echo "(no default route)"
      echo "--- /diagnostic dump ---"
      if [ "$WLAN_OK" != "yes" ] ; then
          echo "sodat firstrun: wlan0 never associated. Check the diagnostic dump above for SSID / signal / reg-domain hints. Aborting bootstrap."
          exit 0
      fi

      # 2. Wait for actual outbound HTTPS reachability — DNS-only checks can
      # succeed against a stale cache while the route isn't usable.
      REACHED=no
      for i in $(seq 1 60); do
          if curl -fsS --max-time 5 -o /dev/null https://raw.githubusercontent.com/hiroyuki-nobutomo/sodat_control/main/VERSION; then
              REACHED=yes; break
          fi
          sleep 5
      done
      echo "post-reach wait: $(date -Is) REACHED=$REACHED"
      if [ "$REACHED" != "yes" ] ; then
          echo "sodat firstrun: never reached raw.githubusercontent.com; aborting bootstrap."
          exit 0
      fi

      # 3. Locate the user's home (created by cloud-init's cc_users_groups,
      # which runs before runcmd).
      SODAT_HOME=$(getent passwd "$SODAT_USER" | cut -d: -f6)
      if [ -z "$SODAT_HOME" ]; then
          echo "sodat firstrun: user '$SODAT_USER' has no home directory yet; aborting."
          exit 0
      fi

      # 4. Move the service-account key into the user's secrets dir.
      SECRETS_DIR="$SODAT_HOME/sensor_sfc/secrets"
      install -d -o "$SODAT_USER" -g "$SODAT_USER" -m 700 "$SECRETS_DIR"
      SA_PATH="$SECRETS_DIR/service_account.json"
      mv /etc/sodat-firstrun/service_account.json "$SA_PATH"
      rmdir /etc/sodat-firstrun 2>/dev/null || true
      chown "$SODAT_USER":"$SODAT_USER" "$SA_PATH"
      chmod 600 "$SA_PATH"

      # 5. Run the Sodat web installer. We're already root from cloud-init, so
      # we don't sudo. SUDO_USER is what bootstrap.sh inspects to figure out
      # which non-root account owns the install — set it explicitly.
      echo "running bootstrap as root with SUDO_USER=$SODAT_USER ..."
      # Capture rc before the conditional — an "if !" branch would make $? always 0.
      SUDO_USER="$SODAT_USER" bash -c \
          'curl -fsSL https://raw.githubusercontent.com/hiroyuki-nobutomo/sodat_control/main/bootstrap.sh | bash'
      bootstrap_rc=$?
      if [ "$bootstrap_rc" -ne 0 ]; then
          echo "sodat firstrun: bootstrap.sh failed (exit=$bootstrap_rc). Re-run later with:"
          echo "  SUDO_USER=$SODAT_USER bash -c 'curl -fsSL https://raw.githubusercontent.com/hiroyuki-nobutomo/sodat_control/main/bootstrap.sh | bash'"
          exit 0
      fi

      # 5b. Reclaim ownership of the install tree before runuser-as-sodat
      # touches it. bootstrap.sh + 01_install_update.sh run as root and an
      # earlier version left config.yaml root-owned, causing every Step 6-8
      # util_config.py write to fail with PermissionError. 01_install_update
      # now chowns at the source, but this belt-and-suspenders line keeps
      # the next-Pi rollout safe even when an older install script is in
      # the repo.
      chown -R "$SODAT_USER":"$SODAT_USER" "$SODAT_HOME/sensor_sfc" 2>/dev/null || true

      # 6. Derive device_id from hostname (s05 -> S05, a01 -> A01).
      HOSTNAME_DERIVED=$(hostname | tr '[:lower:]' '[:upper:]' | sed -nE 's/^([A-Z][0-9]+)$/\1/p')
      if [ -n "$HOSTNAME_DERIVED" ] && [ -d "$SODAT_HOME/sensor_sfc/.venv" ]; then
          runuser -u "$SODAT_USER" -- \
              "$SODAT_HOME/sensor_sfc/.venv/bin/python3" \
              "$SODAT_HOME/sensor_sfc/scripts/util_config.py" \
              --device-id "$HOSTNAME_DERIVED" || true
      fi

      # 7. Trim config.yaml's sensors[] to the researcher-selected subset.
      if [ -n "$SODAT_SENSORS" ] && [ "$SODAT_SENSORS" != "all" ] && [ -d "$SODAT_HOME/sensor_sfc/.venv" ]; then
          runuser -u "$SODAT_USER" -- \
              "$SODAT_HOME/sensor_sfc/.venv/bin/python3" \
              "$SODAT_HOME/sensor_sfc/scripts/util_set_sensors.py" \
              --keep "$SODAT_SENSORS" \
              --config "$SODAT_HOME/sensor_sfc/config.yaml" || true
      fi

      # 8. Point this device at the lab-wide master spreadsheet + Drive
      # folders. config.yaml.template ships REPLACE_WITH_* placeholders,
      # so an empty env var here surfaces as a loud startup failure on
      # the Pi rather than a silent write to the wrong Drive. Each ID
      # is applied independently so one failure doesn't block the rest.
      apply_util_config() {
          local flag="$1" value="$2"
          [ -z "$value" ] && return 0
          [ -d "$SODAT_HOME/sensor_sfc/.venv" ] || return 0
          runuser -u "$SODAT_USER" -- \
              "$SODAT_HOME/sensor_sfc/.venv/bin/python3" \
              "$SODAT_HOME/sensor_sfc/scripts/util_config.py" \
              "$flag" "$value" || true
      }
      apply_util_config --spreadsheet-id    "$SODAT_SPREADSHEET_ID"
      apply_util_config --data-folder-id    "$SODAT_DATA_FOLDER_ID"
      apply_util_config --images-folder-id  "$SODAT_IMAGES_FOLDER_ID"

      # 9. Reboot so the firmware re-reads /boot/firmware/config.txt —
      # 01_install_update.sh appends 'dtparam=i2c_arm=on', but the kernel
      # only picks it up on the NEXT boot, so /dev/i2c-1 is missing until
      # then. cloud-init tracks instance-id, so runcmd does not re-fire.
      echo "=== sodat firstrun: rebooting to apply firmware-level config (I2C) $(date -Is) ==="
      systemctl reboot

runcmd:
  - [ /usr/local/sbin/sodat-firstrun.sh ]

# <<< END SODAT PASTE <<<
`;

function checkToken(req) {
  const expected = process.env.SODAT_ACCESS_TOKEN;
  if (!expected) {
    return {
      ok: false, status: 500,
      msg: "SODAT_ACCESS_TOKEN env var is not set on this Vercel project. " +
           "Set it in Project Settings -> Environment Variables (any random " +
           "string), then redeploy. Researchers append ?token=<that-value> to " +
           "the page URL.",
    };
  }
  const provided = typeof req.query.token === "string" ? req.query.token : "";
  if (!provided) {
    return {
      ok: false, status: 401,
      msg: "Missing access token. Append ?token=<your-lab-token> to the URL " +
           "(get it from the lab admin).",
    };
  }
  // Constant-time comparison to avoid timing side channels on the token.
  const a = Buffer.from(expected, "utf-8");
  const b = Buffer.from(provided, "utf-8");
  if (a.length !== b.length || !timingSafeEqual(a, b)) {
    return { ok: false, status: 401, msg: "Invalid access token." };
  }
  return { ok: true };
}

function fail(res, status, message) {
  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");
  res.status(status).send(`# sodat-firstrun error: ${message}\n`);
}

export default function handler(req, res) {
  if (req.method !== "GET") {
    return fail(res, 405, "Method not allowed (use GET).");
  }

  const auth = checkToken(req);
  if (!auth.ok) {
    return fail(res, auth.status, auth.msg);
  }

  // Validate the SA env early so a paste error fails here instead of producing
  // a broken SD card. Reuses the same loader the dashboard uses.
  let saB64;
  try {
    decodeServiceAccountCreds();
    saB64 = process.env.SODAT_SERVICE_ACCOUNT_JSON_B64;
  } catch (e) {
    return fail(res, 500, e.message);
  }

  const rawUser = typeof req.query.user === "string" ? req.query.user : "sodat";
  if (!USER_RE.test(rawUser)) {
    return fail(res, 400, `Invalid user "${rawUser}": must match ${USER_RE}.`);
  }

  // Sensor selection. "all" (or missing) means leave config.yaml's sensors
  // list untouched on the Pi. Unknown names are rejected so a typo surfaces
  // early instead of silently producing a Pi that runs zero sensors.
  const rawSensors = typeof req.query.sensors === "string" ? req.query.sensors : "all";
  let sensorsValue;
  if (rawSensors.trim().toLowerCase() === "all" || rawSensors.trim() === "") {
    sensorsValue = "all";
  } else {
    const requested = rawSensors.split(",").map((s) => s.trim()).filter(Boolean);
    const unknown = requested.filter((s) => !KNOWN_SENSORS.has(s));
    if (unknown.length) {
      return fail(res, 400,
        `Unknown sensor type(s): ${unknown.join(", ")}. ` +
        `Supported: ${[...KNOWN_SENSORS].join(", ")} (or "all").`
      );
    }
    if (requested.length === 0) {
      return fail(res, 400, 'sensors=" " — pick at least one, or use sensors=all.');
    }
    sensorsValue = [...new Set(requested)].join(",");
  }

  // Strip any whitespace from the b64 — operators sometimes paste with hard
  // wraps, and a multi-line scalar would break the YAML structure.
  const cleanSaB64 = saB64.replace(/\s+/g, "");

  // Validate Drive/Sheets IDs from env — anything but FILE_ID_RE could
  // smuggle a newline into the sourced /etc/sodat-firstrun.env and execute
  // as root, plus typos here cause silent 404s at upload time which is
  // exactly the bug that triggered this audit. Empty string is allowed
  // (template's placeholder will catch it at Pi-side startup).
  const driveIdEnv = (name) => {
    const v = process.env[name];
    if (v === undefined || v === "") return "";
    if (!FILE_ID_RE.test(v)) {
      throw new Error(`${name} env var contains invalid characters; expected ${FILE_ID_RE}.`);
    }
    return v;
  };
  let spreadsheetId, dataFolderId, imagesFolderId;
  try {
    spreadsheetId  = driveIdEnv("SODAT_SPREADSHEET_ID");
    dataFolderId   = driveIdEnv("SODAT_DATA_FOLDER_ID");
    imagesFolderId = driveIdEnv("SODAT_IMAGES_FOLDER_ID");
  } catch (e) {
    return fail(res, 500, e.message);
  }

  const filled = TEMPLATE
    .replace("__SODAT_USER__", rawUser)
    .replace("__SA_JSON_B64__", cleanSaB64)
    .replace("__SODAT_SENSORS__", sensorsValue)
    .replace("__SPREADSHEET_ID__",   spreadsheetId)
    .replace("__DATA_FOLDER_ID__",   dataFolderId)
    .replace("__IMAGES_FOLDER_ID__", imagesFolderId);

  res.setHeader("Content-Type", "text/yaml; charset=utf-8");
  res.setHeader("Content-Disposition", 'attachment; filename="sodat-user-data-snippet.yaml"');
  res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate");
  res.status(200).send(filled);
}
