// Vercel Serverless Function: GET /api/firstrun?user=<unix-username>&token=<access-token>
//
// Returns a cloud-init user-data snippet pre-filled with the project's
// service-account key (read from the SODAT_SERVICE_ACCOUNT_JSON_B64 env var,
// set in the Vercel dashboard) and the requested Pi Imager username.
//
// The endpoint is still called /api/firstrun for URL stability with the
// older firstrun.sh flow — the payload is now YAML (cloud-init user-data),
// because Raspberry Pi Imager v2.0+ ships cloud-init instead of firstrun.sh.
//
// Access is gated by a shared lab token (SODAT_ACCESS_TOKEN env var). Lab
// admins distribute the token to researchers as part of the URL:
//     https://<host>/?token=<the-secret>
// — that way researchers don't have to type the token, but knowing the URL
// (without the token) is not enough to extract the service-account key.
// Token rotation = change the env var and redeploy; old links die instantly.
//
// The cloud-init snippet template is inlined below (rather than read at
// request time from a sibling .yaml.template file via includeFiles).
// Two earlier deploys failed with FUNCTION_INVOCATION_FAILED because the
// .yaml.template file was not making it into the function bundle, and the
// inlined form sidesteps Vercel's file-tracing entirely.

import { timingSafeEqual } from "node:crypto";

// Linux usernames: lowercase letter first, then [a-z0-9_-], up to 32 chars.
const USER_RE = /^[a-z][a-z0-9_-]{0,31}$/;

// Sensor types the project currently supports. Must stay in sync with
// src/sensors/*.py and with KNOWN_SENSORS in docs/index.html (the Step 3
// checkbox list).
// (Mock is intentionally excluded — it's for unit tests, not field deployment.)
const KNOWN_SENSORS = new Set([
  "BME280",
  "TDSN7200",
  "TDSN7300",
  "IWS660CS",
  "Camera",
  "SerialJSON",
]);

// Cloud-init user-data snippet. Use String.raw so backslash line-continuations
// inside the embedded bash script survive intact. Placeholders __SODAT_USER__,
// __SA_JSON_B64__, __SODAT_SENSORS__ are filled in below.
const TEMPLATE = String.raw`# ============================================================================
# Sodat Sensor SFC — cloud-init user-data snippet (zero-touch SD-card setup)
# ============================================================================
#
# DO NOT EDIT THIS FILE BY HAND on a researcher PC. It is a snippet meant to
# be appended to the 'user-data' file that Raspberry Pi Imager v2.0+ writes
# to the SD card's "bootfs" partition (when you used the OS-customisation
# panel).
#
# The web setup page generates a ready-to-paste copy of this file with your
# project's service_account.json already embedded as base64. Use that — do
# not edit this template by hand unless you are the maintainer.
# ============================================================================

# >>> BEGIN SODAT PASTE — APPEND TO /boot/firmware/user-data >>>
# Sodat first-boot bootstrap. Safe to re-apply: the wizard replaces content
# between the BEGIN/END SODAT PASTE markers. Do not touch the markers.

write_files:
  - path: /etc/sodat-firstrun.env
    owner: root:root
    permissions: '0600'
    content: |
      SODAT_USER=__SODAT_USER__
      SODAT_SENSORS=__SODAT_SENSORS__
  - path: /etc/sodat-firstrun/service_account.json
    owner: root:root
    permissions: '0600'
    encoding: b64
    content: __SA_JSON_B64__
  - path: /usr/local/sbin/sodat-firstrun.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      # Sodat first-boot bootstrap, invoked by cloud-init's runcmd phase.
      # cloud-init runs runcmd as root, so we don't need sudo here — Pi Imager
      # v2's user-data does not grant the created user NOPASSWD sudo, and a
      # plain "sudo bash" inside this script would block on a password prompt
      # with no tty (which is what happened on the first deploy).
      set -u
      SODAT_LOG=/var/log/sodat-firstrun.log
      exec >>"$SODAT_LOG" 2>&1
      echo "=== sodat firstrun: $(date -Is) (clock may be unsynced) ==="

      # Load SODAT_USER / SODAT_SENSORS written above.
      . /etc/sodat-firstrun.env

      # 1. Trigger NTP and wait for the clock to actually sync. Pi 5 boots with
      # an unset RTC, so the first cloud-init runcmd typically runs ~4 weeks in
      # the past, which then breaks apt's sig-validity check and HTTPS certs.
      timedatectl set-ntp true 2>/dev/null || true
      for i in $(seq 1 60); do
          [ "$(timedatectl show -p NTPSynchronized --value 2>/dev/null)" = "yes" ] && break
          sleep 5
      done
      echo "post-ntp wait: $(date -Is) (NTPSynchronized=$(timedatectl show -p NTPSynchronized --value 2>/dev/null))"

      # 2. Wait for actual outbound HTTPS reachability — DNS-only checks can
      # succeed against a stale cache while the route isn't usable.
      REACHED=no
      for i in $(seq 1 60); do
          if curl -fsS --max-time 5 -o /dev/null https://raw.githubusercontent.com/hiroyuki-nobutomo/sodat_control/main/VERSION; then
              REACHED=yes; break
          fi
          sleep 5
      done
      echo "post-reach wait: $(date -Is) REACHED=$REACHED"
      if [ "$REACHED" != "yes" ] ; then
          echo "sodat firstrun: never reached raw.githubusercontent.com; aborting bootstrap."
          exit 0
      fi

      # 3. Locate the user's home (created by cloud-init's cc_users_groups,
      # which runs before runcmd).
      SODAT_HOME=$(getent passwd "$SODAT_USER" | cut -d: -f6)
      if [ -z "$SODAT_HOME" ]; then
          echo "sodat firstrun: user '$SODAT_USER' has no home directory yet; aborting."
          exit 0
      fi

      # 4. Move the service-account key into the user's secrets dir.
      SECRETS_DIR="$SODAT_HOME/sensor_sfc/secrets"
      install -d -o "$SODAT_USER" -g "$SODAT_USER" -m 700 "$SECRETS_DIR"
      SA_PATH="$SECRETS_DIR/service_account.json"
      mv /etc/sodat-firstrun/service_account.json "$SA_PATH"
      rmdir /etc/sodat-firstrun 2>/dev/null || true
      chown "$SODAT_USER":"$SODAT_USER" "$SA_PATH"
      chmod 600 "$SA_PATH"

      # 5. Run the Sodat web installer. We're already root from cloud-init, so
      # we don't sudo. SUDO_USER is what bootstrap.sh inspects to figure out
      # which non-root account owns the install — set it explicitly.
      echo "running bootstrap as root with SUDO_USER=$SODAT_USER ..."
      if ! SUDO_USER="$SODAT_USER" bash -c \
          'curl -fsSL https://raw.githubusercontent.com/hiroyuki-nobutomo/sodat_control/main/bootstrap.sh | bash'; then
          echo "sodat firstrun: bootstrap.sh failed (exit=$?). Re-run later with:"
          echo "  SUDO_USER=$SODAT_USER bash -c 'curl -fsSL https://raw.githubusercontent.com/hiroyuki-nobutomo/sodat_control/main/bootstrap.sh | bash'"
          exit 0
      fi

      # 6. Derive device_id from hostname (s05 -> S05, a01 -> A01).
      HOSTNAME_DERIVED=$(hostname | tr '[:lower:]' '[:upper:]' | sed -nE 's/^([A-Z][0-9]+)$/\1/p')
      if [ -n "$HOSTNAME_DERIVED" ] && [ -d "$SODAT_HOME/sensor_sfc/.venv" ]; then
          runuser -u "$SODAT_USER" -- \
              "$SODAT_HOME/sensor_sfc/.venv/bin/python3" \
              "$SODAT_HOME/sensor_sfc/scripts/util_config.py" \
              --device-id "$HOSTNAME_DERIVED" || true
      fi

      # 7. Trim config.yaml's sensors[] to the researcher-selected subset.
      if [ -n "$SODAT_SENSORS" ] && [ "$SODAT_SENSORS" != "all" ] && [ -d "$SODAT_HOME/sensor_sfc/.venv" ]; then
          runuser -u "$SODAT_USER" -- \
              "$SODAT_HOME/sensor_sfc/.venv/bin/python3" \
              "$SODAT_HOME/sensor_sfc/scripts/util_set_sensors.py" \
              --keep "$SODAT_SENSORS" \
              --config "$SODAT_HOME/sensor_sfc/config.yaml" || true
      fi

      # 8. Reboot so the firmware re-reads /boot/firmware/config.txt — 01_install_update.sh
      # appends 'dtparam=i2c_arm=on' to enable I2C, but the kernel/firmware only picks
      # that up on the NEXT boot, which means BME280 (the I2C sensor) returns
      # "No such file or directory: '/dev/i2c-1'" until then. Bouncing here makes
      # the very first cloud-init pass a complete, runnable install.
      # cloud-init tracks instance-id; the post-reboot boot does not re-run runcmd.
      echo "=== sodat firstrun: rebooting to apply firmware-level config (I2C) $(date -Is) ==="
      systemctl reboot

runcmd:
  - [ /usr/local/sbin/sodat-firstrun.sh ]

# <<< END SODAT PASTE <<<
`;

function checkToken(req) {
  const expected = process.env.SODAT_ACCESS_TOKEN;
  if (!expected) {
    return {
      ok: false, status: 500,
      msg: "SODAT_ACCESS_TOKEN env var is not set on this Vercel project. " +
           "Set it in Project Settings -> Environment Variables (any random " +
           "string), then redeploy. Researchers append ?token=<that-value> to " +
           "the page URL.",
    };
  }
  const provided = typeof req.query.token === "string" ? req.query.token : "";
  if (!provided) {
    return {
      ok: false, status: 401,
      msg: "Missing access token. Append ?token=<your-lab-token> to the URL " +
           "(get it from the lab admin).",
    };
  }
  // Constant-time comparison to avoid timing side channels on the token.
  const a = Buffer.from(expected, "utf-8");
  const b = Buffer.from(provided, "utf-8");
  if (a.length !== b.length || !timingSafeEqual(a, b)) {
    return { ok: false, status: 401, msg: "Invalid access token." };
  }
  return { ok: true };
}

function fail(res, status, message) {
  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");
  res.status(status).send(`# sodat-firstrun error: ${message}\n`);
}

// Cloud-init's b64 decoder is lenient about whitespace, but YAML parsers
// don't like a multi-kilobyte scalar that wraps awkwardly. Strip any
// whitespace/newlines from the env-var value so the rendered user-data has
// a clean single-line base64 string under `content:`.
function normalizeB64(s) {
  return s.replace(/\s+/g, "");
}

export default function handler(req, res) {
  try {
    return handleImpl(req, res);
  } catch (e) {
    // Surface uncaught exceptions instead of letting Vercel return its
    // generic FUNCTION_INVOCATION_FAILED page — the original cause is
    // otherwise only visible in Vercel logs.
    const detail = (e && (e.stack || e.message)) || String(e);
    try {
      return fail(res, 500, `unhandled in /api/firstrun: ${detail}`);
    } catch {
      throw e;
    }
  }
}

function handleImpl(req, res) {
  if (req.method !== "GET") {
    return fail(res, 405, "Method not allowed (use GET).");
  }

  // Tiny diagnostic endpoint so we can confirm the function is even reachable
  // without exercising the env-var / template path. Use ?diag=1.
  if (req.query && req.query.diag) {
    res.setHeader("Content-Type", "text/plain; charset=utf-8");
    res.setHeader("Cache-Control", "no-store");
    return res.status(200).send(
      `sodat firstrun diag ok\n` +
      `node=${process.version}\n` +
      `template_bytes=${TEMPLATE.length}\n` +
      `has_access_token=${!!process.env.SODAT_ACCESS_TOKEN}\n` +
      `has_sa_b64=${!!process.env.SODAT_SERVICE_ACCOUNT_JSON_B64}\n`
    );
  }

  const auth = checkToken(req);
  if (!auth.ok) {
    return fail(res, auth.status, auth.msg);
  }

  const saB64 = process.env.SODAT_SERVICE_ACCOUNT_JSON_B64;
  if (!saB64) {
    return fail(res, 500,
      "SODAT_SERVICE_ACCOUNT_JSON_B64 env var is not set on this Vercel project. " +
      "Set it in the Vercel dashboard (Project Settings -> Environment Variables) " +
      "to the base64-encoded contents of service_account.json."
    );
  }

  // Validate the env var actually decodes to a service-account key —
  // catches paste errors early instead of producing a broken SD card.
  let decoded;
  try {
    decoded = Buffer.from(saB64, "base64").toString("utf-8");
    const obj = JSON.parse(decoded);
    if (obj.type !== "service_account") {
      throw new Error('JSON is missing "type": "service_account"');
    }
    if (!obj.client_email || !obj.private_key) {
      throw new Error("JSON is missing client_email or private_key");
    }
  } catch (e) {
    return fail(res, 500,
      `SODAT_SERVICE_ACCOUNT_JSON_B64 does not contain a valid service-account JSON: ${e.message}`
    );
  }

  const rawUser = typeof req.query.user === "string" ? req.query.user : "sodat";
  if (!USER_RE.test(rawUser)) {
    return fail(res, 400,
      `Invalid user "${rawUser}": must match ${USER_RE}.`
    );
  }

  // Sensor selection. "all" (or missing) means leave config.yaml's sensors
  // list untouched on the Pi. Otherwise the value must be a CSV of known
  // sensor types — unknown names are rejected to surface typos early instead
  // of silently producing a Pi that runs zero sensors.
  const rawSensors = typeof req.query.sensors === "string" ? req.query.sensors : "all";
  let sensorsValue;
  if (rawSensors.trim().toLowerCase() === "all" || rawSensors.trim() === "") {
    sensorsValue = "all";
  } else {
    const requested = rawSensors.split(",").map((s) => s.trim()).filter(Boolean);
    const unknown = requested.filter((s) => !KNOWN_SENSORS.has(s));
    if (unknown.length) {
      return fail(res, 400,
        `Unknown sensor type(s): ${unknown.join(", ")}. ` +
        `Supported: ${[...KNOWN_SENSORS].join(", ")} (or "all").`
      );
    }
    if (requested.length === 0) {
      return fail(res, 400, 'sensors=" " — pick at least one, or use sensors=all.');
    }
    sensorsValue = [...new Set(requested)].join(",");
  }

  const filled = TEMPLATE
    .replace("__SODAT_USER__", rawUser)
    .replace("__SA_JSON_B64__", normalizeB64(saB64))
    .replace("__SODAT_SENSORS__", sensorsValue);

  res.setHeader("Content-Type", "text/yaml; charset=utf-8");
  res.setHeader("Content-Disposition", 'attachment; filename="sodat-user-data-snippet.yaml"');
  res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate");
  res.status(200).send(filled);
}
